version: '3.8'

services:
  fastapi:
    container_name: fastapi-kafka
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - kafka-net

networks:
  kafka-net:
    external: true
